
version: "2"
networks:
  internal:
    driver: bridge
services: 
  rlcfront:
    container_name: "rlcfront"
    image: "node:lts-alpine"
    working_dir: /app
    restart: always
    volumes:
      - "../../vue:/app"
    command: "npm run serve"
    networks:
      - internal
    ports:
      - "8081:8080"
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.rlcfront.rule=Host(`rlc.alvitre.com.br`)
      - traefik.http.services.rlcfront.loadbalancer.server.port=8080